name = "ModelKit"
uuid = "4ba45528-c0ec-4d03-9092-87a18bf21995"
authors = ["Sascha Timme <sascha@timme.xyz>"]
version = "0.1.0"

[deps]
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
